/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SOLVERS_SolverKrylov */

#ifndef _Included_SOLVERS_SolverKrylov
#define _Included_SOLVERS_SolverKrylov
#ifdef __cplusplus
extern "C" {
#endif
#undef SOLVERS_SolverKrylov_sizeof_num
#define SOLVERS_SolverKrylov_sizeof_num 8L
/*
 * Class:     SOLVERS_SolverKrylov
 * Method:    solveKrylovC
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_SOLVERS_SolverKrylov_solveKrylovC
  (JNIEnv *, jobject, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
