/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SOLVERS_SolverQR */

#ifndef _Included_SOLVERS_SolverQR
#define _Included_SOLVERS_SolverQR
#ifdef __cplusplus
extern "C" {
#endif
#undef SOLVERS_SolverQR_sizeof_num
#define SOLVERS_SolverQR_sizeof_num 8L
/*
 * Class:     SOLVERS_SolverQR
 * Method:    solveQRC
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_SOLVERS_SolverQR_solveQRC
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint);

/*
 * Class:     SOLVERS_SolverQR
 * Method:    erfC
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_SOLVERS_SolverQR_erfC
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
