/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SOLVERS_SolverODE */

#ifndef _Included_SOLVERS_SolverODE
#define _Included_SOLVERS_SolverODE
#ifdef __cplusplus
extern "C" {
#endif
#undef SOLVERS_SolverODE_sizeof_num
#define SOLVERS_SolverODE_sizeof_num 8L
/*
 * Class:     SOLVERS_SolverODE
 * Method:    solveODEC
 * Signature: (Ljava/nio/ByteBuffer;DII)D
 */
JNIEXPORT jdouble JNICALL Java_SOLVERS_SolverODE_solveODEC
  (JNIEnv *, jobject, jobject, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
